import type { LanguageCode } from "./i18n";

export const copy = {
  ko: {
    products: "제품",
    all: "전체 제품 보기",
    about: "쿠피 소개",
    support: "지원",
    policies: "개인정보 및 약관",
    menu: "메뉴",
    close: "닫기",
    title: "일상에 쓸모를,\n순간에 즐거움을.",
    intro: "읽고, 즐기고, 일하는 시간을 위한\n앱과 웹서비스를 만듭니다.",
    explore: "쿠피 제품 둘러보기",
    selected: "쿠피가 만든 경험",
    selectedBody: "당신의 하루에 어울리는 작은 발견.",
    detail: "자세히 보기",
    reader: "쿠피리더",
    readerTitle: "읽는 순간을,\n나에게 맞게.",
    readerBody:
      "나만의 서재부터 편안한 글꼴, 음성 듣기까지. TXT와 EPUB을 내가 좋아하는 방식으로 읽어 보세요.",
    apps: "앱과 게임",
    cases: "웹사이트 제작 사례",
    casesBody: "다양한 분야를 위한 웹사이트와 서비스 디자인을 소개합니다.",
    catalogTitle: "취향에 맞는 즐거움.\n필요에 맞는 도구.",
    catalogBody: "쿠피의 앱과 게임, 그리고 웹사이트 제작 사례를 만나 보세요.",
    upcoming: "출시 준비 중",
    testing: "테스트 중",
    live: "스토어에서 보기",
    case: "제작 사례",
    concept: "콘셉트",
    valuesTitle: "작은 디테일로,\n더 좋은 하루를.",
    values: ["쉽게 시작하고", "내 방식대로 쓰고", "다시 찾고 싶도록"],
    valueBodies: [
      "첫 화면에서 무엇을 할 수 있는지 분명하게.",
      "읽는 취향부터 즐기는 방식까지 자연스럽게.",
      "손이 자주 가는 기능을 꾸준히 다듬습니다.",
    ],
    contactTitle: "쿠피에 전하고 싶은 이야기가 있나요?",
    contactBody: "제품을 쓰며 느낀 점부터 새로운 아이디어까지 들려주세요.",
    contact: "문의하기",
    policyTitle: "서비스별 개인정보 및 약관",
    policyBody:
      "이용 중인 서비스를 선택해 데이터 처리 방식과 이용 안내를 확인하세요.",
    privacy: "개인정보처리방침",
    terms: "이용약관",
    website: "쿠피 웹사이트",
    supportTitle: "무엇을 도와드릴까요?",
    supportBody:
      "앱 이용 문의, 오류 제보, 개인정보 관련 문의를 대표 이메일로 보내 주세요.",
    supportNote:
      "제품명, 기기와 운영체제, 앱 버전, 문제가 발생한 상황을 알려주시면 확인에 도움이 됩니다. 비밀번호나 개인 문서는 보내지 마세요.",
    readerFeatures: [
      "내 책을 담는 서재",
      "넓은 화면에는 두 페이지",
      "편안함도 내 취향대로",
      "눈을 쉬게 하는 음성 듣기",
    ],
    readerFeatureBodies: [
      "TXT·EPUB을 불러오고, 나눠진 책은 묶음으로 정리하세요. 읽던 위치에서 이어 읽을 수 있습니다.",
      "휴대폰부터 태블릿과 폴더블까지. 화면에 맞춰 한 페이지 또는 두 페이지로 읽으세요.",
      "글꼴, 글자 크기, 배경과 페이지 넘김을 조절해 나에게 편안한 독서 환경을 만드세요.",
      "기기에 제공되는 음성을 선택해 책을 들으세요. 사용 가능한 음성과 품질은 기기에 따라 다릅니다.",
    ],
    releaseNote:
      "iOS는 심사 준비 중이며 Android는 비공개 테스트 중입니다. 정식 출시 후 다운로드 링크를 안내합니다.",
    screenshots: "앱 화면 · 예시 도서 사용",
    overview: "제품 소개",
    related: "다른 제품 둘러보기",
    unavailable: "이 제품에 대해 궁금한 점은 쿠피에 문의해 주세요.",
  },
  en: {
    products: "Products",
    all: "All products",
    about: "About Koofy",
    support: "Support",
    policies: "Privacy & terms",
    menu: "Menu",
    close: "Close",
    title: "A little more useful.\nA little more joyful.",
    intro: "Apps and web experiences for the way\nyou read, play, and work.",
    explore: "Explore Koofy",
    selected: "Made by Koofy",
    selectedBody: "Small discoveries for your everyday.",
    detail: "Discover more",
    reader: "Koofy Reader",
    readerTitle: "Your reading.\nYour way.",
    readerBody:
      "Your own library, comfortable typography, and text-to-speech. Read TXT and EPUB books the way you like.",
    apps: "Apps & games",
    cases: "Website projects",
    casesBody: "Website and service design for different kinds of businesses.",
    catalogTitle: "A little play.\nA useful companion.",
    catalogBody: "Discover our apps, games, and website projects.",
    upcoming: "Coming soon",
    testing: "In testing",
    live: "View in store",
    case: "Project",
    concept: "Concept",
    valuesTitle: "Small details.\nBetter days.",
    values: ["Easy to begin", "Make it yours", "Worth coming back to"],
    valueBodies: [
      "A clear first screen that helps you get started.",
      "Room for your reading preferences and ways to play.",
      "Thoughtful improvements to the things you use most.",
    ],
    contactTitle: "Something to share with Koofy?",
    contactBody: "Tell us about your experience or a new idea.",
    contact: "Get in touch",
    policyTitle: "Privacy & terms by service",
    policyBody:
      "Choose a service to learn how it handles data and review its terms.",
    privacy: "Privacy policy",
    terms: "Terms of use",
    website: "Koofy website",
    supportTitle: "How can we help?",
    supportBody: "Contact us about app support, bugs, or privacy questions.",
    supportNote:
      "Include the product, device, operating system, app version, and what happened. Please do not send passwords or private documents.",
    readerFeatures: [
      "A home for your books",
      "Two pages, more room",
      "Comfort is personal",
      "Give your eyes a break",
    ],
    readerFeatureBodies: [
      "Import TXT and EPUB files, group volumes, and continue from your saved reading position.",
      "Read on phones, tablets, and foldables, with one or two pages to suit your screen.",
      "Adjust fonts, text size, background, and page turns to build a comfortable reading experience.",
      "Listen with voices available on your device. Voice availability and quality vary by device.",
    ],
    releaseNote:
      "iOS is being prepared for review and Android is in closed testing. Download links will be available after release.",
    screenshots: "App screens · sample books",
    overview: "About this product",
    related: "Explore other products",
    unavailable: "Contact Koofy to learn more about this product.",
  },
  ja: {
    products: "プロダクト",
    all: "すべての製品",
    about: "Koofyについて",
    support: "サポート",
    policies: "プライバシー・規約",
    menu: "メニュー",
    close: "閉じる",
    title: "日常に便利さを。\nひとときに楽しさを。",
    intro: "読む、遊ぶ、働く時間のための\nアプリとウェブサービスをつくります。",
    explore: "製品を見る",
    selected: "Koofyのつくる体験",
    selectedBody: "毎日に、小さな発見を。",
    detail: "詳しく見る",
    reader: "Koofy Reader",
    readerTitle: "読書を、\n自分らしく。",
    readerBody:
      "自分だけの本棚、読みやすい文字、音声読み上げ。TXTとEPUBを好きなスタイルで。",
    apps: "アプリ・ゲーム",
    cases: "ウェブ制作事例",
    casesBody: "さまざまな分野のウェブサイトとサービスデザイン。",
    catalogTitle: "好みに合う楽しさ。\n必要に合う道具。",
    catalogBody: "Koofyのアプリ、ゲーム、ウェブ制作事例をご覧ください。",
    upcoming: "公開準備中",
    testing: "テスト中",
    live: "ストアで見る",
    case: "制作事例",
    concept: "コンセプト",
    valuesTitle: "小さな工夫で、\nより良い毎日に。",
    values: ["迷わず始める", "自分らしく使う", "また使いたくなる"],
    valueBodies: [
      "最初の画面でできることがわかるように。",
      "読書の好みも遊び方も自然に。",
      "よく使う機能を少しずつ磨きます。",
    ],
    contactTitle: "Koofyに伝えたいことはありますか？",
    contactBody: "使ってみた感想や新しいアイデアをお聞かせください。",
    contact: "お問い合わせ",
    policyTitle: "サービス別プライバシー・規約",
    policyBody: "サービスを選び、データの取り扱いや利用規約をご確認ください。",
    privacy: "プライバシーポリシー",
    terms: "利用規約",
    website: "Koofyウェブサイト",
    supportTitle: "お困りですか？",
    supportBody:
      "アプリの使い方、不具合、プライバシーに関するお問い合わせを受け付けています。",
    supportNote:
      "製品名、端末、OS、アプリのバージョン、発生状況をお知らせください。パスワードや個人の文書は送らないでください。",
    readerFeatures: [
      "本を集める本棚",
      "広い画面で見開き読書",
      "心地よさも自分好みに",
      "目を休めて音声で",
    ],
    readerFeatureBodies: [
      "TXT・EPUBを読み込み、分冊をまとめ、前回の位置から再開できます。",
      "スマートフォン、タブレット、折りたたみ端末に合わせて1ページまたは2ページで読めます。",
      "フォント、文字サイズ、背景、ページめくりを調整できます。",
      "端末に用意された音声で読み上げます。音声の種類と品質は端末によって異なります。",
    ],
    releaseNote:
      "iOSは審査準備中、Androidはクローズドテスト中です。公開後にダウンロードリンクをご案内します。",
    screenshots: "アプリ画面・サンプル書籍",
    overview: "製品について",
    related: "ほかの製品を見る",
    unavailable: "この製品についてはKoofyにお問い合わせください。",
  },
  zh: {
    products: "产品",
    all: "全部产品",
    about: "关于 Koofy",
    support: "支持",
    policies: "隐私与条款",
    menu: "菜单",
    close: "关闭",
    title: "为日常添便利，\n为片刻添乐趣。",
    intro: "为阅读、游戏与工作\n打造应用和网页服务。",
    explore: "探索 Koofy 产品",
    selected: "Koofy 创造的体验",
    selectedBody: "为每一天带来小小的发现。",
    detail: "了解更多",
    reader: "Koofy Reader",
    readerTitle: "阅读，\n随你喜欢。",
    readerBody: "专属书架、舒适字体与语音朗读，用喜欢的方式阅读 TXT 和 EPUB。",
    apps: "应用与游戏",
    cases: "网站设计案例",
    casesBody: "面向不同领域的网站与服务设计。",
    catalogTitle: "合心意的乐趣，\n合需求的工具。",
    catalogBody: "探索我们的应用、游戏与网站设计案例。",
    upcoming: "即将推出",
    testing: "测试中",
    live: "前往商店",
    case: "设计案例",
    concept: "概念设计",
    valuesTitle: "小小细节，\n让每一天更好。",
    values: ["轻松开始", "随心使用", "值得再次打开"],
    valueBodies: [
      "在第一个界面就知道可以做什么。",
      "让阅读偏好与游戏方式自然融入。",
      "持续改进经常使用的功能。",
    ],
    contactTitle: "有什么想与 Koofy 分享的吗？",
    contactBody: "欢迎告诉我们使用感受或新的想法。",
    contact: "联系我们",
    policyTitle: "各服务隐私与条款",
    policyBody: "选择服务，了解数据处理方式与使用条款。",
    privacy: "隐私政策",
    terms: "使用条款",
    website: "Koofy 网站",
    supportTitle: "需要什么帮助？",
    supportBody: "欢迎咨询应用使用、报告问题或询问隐私事项。",
    supportNote:
      "请提供产品名、设备、操作系统、应用版本和问题发生的情况。请勿发送密码或私人文件。",
    readerFeatures: [
      "收藏书籍的书架",
      "大屏双页阅读",
      "舒适由你定义",
      "让眼睛休息一下",
    ],
    readerFeatureBodies: [
      "导入 TXT 和 EPUB，整理分卷，并从上次的位置继续阅读。",
      "适配手机、平板和折叠屏，选择单页或双页阅读。",
      "调整字体、字号、背景和翻页方式。",
      "使用设备提供的语音朗读。可用语音与品质因设备而异。",
    ],
    releaseNote:
      "iOS 正在准备审核，Android 正在封闭测试。正式发布后将提供下载链接。",
    screenshots: "应用画面 · 示例书籍",
    overview: "产品介绍",
    related: "探索其他产品",
    unavailable: "如需了解该产品，请联系 Koofy。",
  },
} satisfies Record<LanguageCode, Record<string, string | string[]>>;

export type Product = {
  slug: string;
  href: string;
  kind: "app" | "case";
  name: string;
  description: string;
  status: string;
  image?: string;
  imageAlt?: string;
  links?: { label: string; href: string }[];
  privacy?: string;
  terms?: string;
  support?: string;
};
export const productSlugs = [
  "bus-pop",
  "koofy-sudoku",
  "slime-strike-force",
  "honeybee",
  "tax-lab",
  "yongs-dining",
  "oren-gym",
  "intranet",
];

import { translations } from "./i18n";
export function getProducts(language: LanguageCode): Product[] {
  const t = copy[language];
  const old = translations[language].home.products;
  const extra = {
    ko: [
      "슬라임특공대",
      "스킬을 조합하고 몰려오는 몬스터를 상대하는 세로형 캐주얼 로그라이크 게임.",
      "허니비",
      "합치는 즐거움을 담은 모바일 머지 게임.",
    ],
    en: [
      "Slime Strike Force",
      "Combine skills and face waves of monsters in a portrait casual roguelike.",
      "Honeybee",
      "A mobile merge game built around the joy of combining.",
    ],
    ja: [
      "スライム特攻隊",
      "スキルを組み合わせてモンスターに挑む縦画面のカジュアルローグライク。",
      "Honeybee",
      "合体する楽しさを詰め込んだモバイルマージゲーム。",
    ],
    zh: [
      "史莱姆特攻队",
      "组合技能，迎战怪物浪潮的竖屏休闲 Roguelike 游戏。",
      "Honeybee",
      "体验合成乐趣的手机合并游戏。",
    ],
  }[language];
  return [
    {
      slug: "koofy-reader",
      href: "/koofy-reader",
      kind: "app",
      name: t.reader,
      description: t.readerBody,
      status: t.upcoming,
      image: "/products/reader-library.webp",
      imageAlt: t.readerFeatures[0],
      privacy: "/koofy-reader/privacy",
      support: "/koofy-reader/support",
    },
    ...old.apps.map(
      (p, i): Product => ({
        ...p,
        slug: productSlugs[i],
        href: `/products/${productSlugs[i]}`,
        kind: "app",
        status: t.live,
        ...(i === 0 ? { privacy: "/bus-pop/privacy" } : {}),
      }),
    ),
    {
      slug: "slime-strike-force",
      href: "/products/slime-strike-force",
      kind: "app",
      name: extra[0],
      description: extra[1],
      status: t.testing,
      privacy: "/slime-strike-force/privacy",
      terms: "/slime-strike-force/terms",
    },
    {
      slug: "honeybee",
      href: "/products/honeybee",
      kind: "app",
      name: extra[2],
      description: extra[3],
      status: t.overview,
      privacy: "/honeybee/privacy",
    },
    ...old.sites.map(
      (p, i): Product => ({
        ...p,
        slug: productSlugs[i + 4],
        href: `/products/${productSlugs[i + 4]}`,
        kind: "case",
        status: i === 3 ? t.concept : t.case,
      }),
    ),
  ];
}
